-- https://www.hackerrank.com/challenges/average-population/problem?isFullScreen=true

-- CREATE TABLE CITY (
--     ID INT AUTO_INCREMENT PRIMARY KEY,
-- 	NAME VARCHAR(255),
-- 	COUNTRYCODE VARCHAR(255),
-- 	DISTRICT VARCHAR(255),
--     POPULATION DECIMAL(20,6)
-- );

-- INSERT INTO CITY (NAME, COUNTRYCODE, DISTRICT, POPULATION)
-- VALUES
--     ("SÃO PAULO", "BR", "PARAÍSO", 20000.45),
--     ("SÃO PAULO", "BR", "PRAÇA DA ÁRVORE", 30000.3),
--     ("SÃO PAULO", "BR", "SAÚDE", 400000.7),
--     ("SÃO PAULO", "BR", "VILA MARIANA", 500000.6);

SELECT FLOOR(AVG(POPULATION)) AS RESULT FROM CITY;

-- POPULATION WOULD NEVER BE A DECIMAL VALUE, BUT WE ARE ACCEPTING
-- THAT TO THE EXERCICE PURPOUSE.
